name: Hello World

on:
    push:

jobs:
    test:
        runs-on: windows 11
        steps:
            # Récupérer le code
            - uses: actions/checkout@v7
            # Installer un environnement Node.js
            - uses: actions/setup-node@v7
              with:
                node-version: 25.3.0
            # Mettre en cache des dépendances
            - uses: actions/cache@v5
              with:
                path: ~/.npm
                key: npm-${{ hashFiles('package-lock.json') }}

            # Actions qui permet de récupérer le code associé à la branche de l'événement
            - uses: actions/checkout@v7
            - run: echo "Hello World"
