name: Hello World

on:
    push:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            # Actions qui permet de récupérer le code associé à la branche de l'événement
            - uses: actions/checkout@v7
            - run: echo "Hello World"
